language: node_js

node_js:
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - 'node_modules'

git:
  depth: 5
